"""compile_to_t5asm.py — FlowCode → 5500FP assembly compiler.

Phase 7b-1 MVP: translates a WordStream (with aliased flow_symbols metadata)
to 5500FP assembly text (.t5asm).

Entry-point semantics:
  - Finds the first flow_terminator with is_entry=True (in insertion order)
  - Emits PRINT_CHAR for each character of its label, PRINT_NL, then HALT
  - Raises CompileError if no entry terminator exists

Syscall conventions (from c_emulator/include/isa.h):
  SYS_PRINT_CHAR = 3   — R1=3, R2=char_code, SYSCALL
  SYS_PRINT_NL   = 6   — R1=6, SYSCALL

Later 7b phases extend this to walk flow edges, dispatch handlers,
and emit PIGART rendering syscalls.

Date: 2026-06-19, Adelaide
Authors: Stevo (SkepticusMaximus) + Claude (Anthropic)
"""

from __future__ import annotations

import datetime
import os
from typing import Optional, TYPE_CHECKING

if TYPE_CHECKING:
    from word_stream import WordStream

# ---------------------------------------------------------------------------
# Public exception
# ---------------------------------------------------------------------------

class CompileError(Exception):
    """Raised when a WordStream cannot be compiled to .t5asm."""


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

_SYS_PRINT_CHAR = 3
_SYS_PRINT_NL   = 6


def _find_entry_terminator(stream: 'WordStream') -> Optional[dict]:
    """Return the first flow_terminator with is_entry=True, or None.

    Iterates stream._flow_meta in insertion order (Python 3.7+ dict).
    """
    flow_meta = getattr(stream, '_flow_meta', None) or {}
    for sym in flow_meta.values():
        if sym.get('kind') != 'flow_terminator':
            continue
        is_entry = False
        for p in sym.get('properties', []):
            if p.get('name') == 'is_entry':
                is_entry = bool(p.get('value', False))
                break
        if is_entry:
            return sym
    return None


def _emit_print_char_sequence(label: str) -> list[str]:
    """Emit the PRINT_CHAR stanza for label (may be empty).

    Pattern:
        LI   R1, 3          ; SYSCALL PRINT_CHAR
        LI   R2, <code>     ; '<ch>'
        SYSCALL
        LI   R2, <code>     ; '<ch>'
        SYSCALL
        ...

    R1 is set once at the top of the sequence.
    Subsequent characters only change R2.
    """
    lines = []
    if not label:
        return lines

    chars = list(label)
    # First char — set R1 once
    first = chars[0]
    code  = ord(first)
    ch_repr = repr(first)
    lines.append(f'    LI   R1, {_SYS_PRINT_CHAR:<6}  ; SYSCALL PRINT_CHAR')
    lines.append(f'    LI   R2, {code:<6}  ; {ch_repr}')
    lines.append( '    SYSCALL')
    # Remaining chars — reuse R1
    for ch in chars[1:]:
        code    = ord(ch)
        ch_repr = repr(ch)
        lines.append(f'    LI   R2, {code:<6}  ; {ch_repr}')
        lines.append( '    SYSCALL')
    return lines


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def compile_wordstream_to_t5asm(stream: 'WordStream',
                                 source_path: str = '<in-memory>') -> str:
    """Translate a WordStream to 5500FP assembly text.

    Phase 7b-1 MVP: finds the first flow_terminator with is_entry=True,
    emits PRINT_CHAR for each character of its label, PRINT_NL, then HALT.

    Later 7b phases extend this to walk flow edges, dispatch handlers,
    and emit PIGART rendering syscalls.

    Args:
        stream:      the canonical WordStream (must have _flow_meta set).
        source_path: path to the .ternoo file (used in header comment only).

    Returns:
        t5asm text ready to write to a .t5asm file.

    Raises:
        CompileError: if no flow_terminator with is_entry=True exists.
    """
    # ── Find entry terminator ─────────────────────────────────────────────
    entry = _find_entry_terminator(stream)
    if entry is None:
        raise CompileError("No entry terminator found")

    label = entry.get('label', '') or ''
    ex    = entry.get('x', 0)
    ey    = entry.get('y', 0)

    # ── Build header ──────────────────────────────────────────────────────
    now      = datetime.datetime.now().astimezone()
    iso_now  = now.strftime('%Y-%m-%dT%H:%M:%S%z')
    src_name = os.path.basename(source_path) if source_path != '<in-memory>' else source_path

    lines = [
        '; Auto-generated by FlowCode compiler',
        f'; Source:    {src_name}',
        f'; Generated: {iso_now}',
        f'; Entry:     flow_terminator "{label}" at position ({ex}, {ey})',
        '; Phase:     7b-1 (PRINT_CHAR + HALT only)',
        '',
        'main:',
    ]

    # ── Emit body ─────────────────────────────────────────────────────────
    if label:
        lines.append(f'    ; Print "{label}"')
        lines.extend(_emit_print_char_sequence(label))
    else:
        lines.append('    ; (empty label — just emit newline)')

    lines.append(f'    LI   R1, {_SYS_PRINT_NL:<6}  ; SYSCALL PRINT_NL')
    lines.append( '    SYSCALL')
    lines.append( '    HALT')
    lines.append('')   # trailing newline

    return '\n'.join(lines)
