#!/usr/bin/env python3
"""gen_mandelbrot_t5asm.py  [ISA NOTE: register fields are 4 balanced
trits — only R0-R40 are encodable; R1-R7 are syscall args.  This program
uses R18-R39 for state and stays inside the lawful window.] — emit mandelbrot_screensaver.t5asm.

A fully native TernOO-5500FP screensaver: integer fixed-point Mandelbrot
rendered through PIGART DRAW_RECT with Fractint-style rotating palette,
cycling through six classic views, one minute each.

All arithmetic is 24-trit integer (fixed point, SCALE = 64) — this is the
5500FP doing real mathematics, not a host-side shortcut.  Test mode
(test_mode word != 0) computes view 0 only, prints the iteration-buffer
checksum, and halts — verified against an independent Python reference in
test_mandelbrot.py.

Usage:  python3 gen_mandelbrot_t5asm.py [out.t5asm] [--test]

Date: 2026-07-03, Adelaide
Authors: Stevo (SkepticusMaximus) + Claude (Anthropic)
"""

import sys

S = 64                    # fixed-point scale
GW, GH = 64, 48           # grid cells
CELL = 8                  # pixels per cell → 512x384 window
MAXIT = 24
NPAL = 24
VIEW_MS = 60000           # one minute per view
PHASE_MS = 80             # palette rotation speed

# Six classic views: (center_x, center_y, half_width) in real units.
VIEWS_REAL = [
    (-0.50,  0.000, 1.60),          # the full set
    (-0.745, 0.113, 0.0700),        # seahorse valley
    (-0.170, 1.0405, 0.0500),       # top bulb tendrils
    ( 0.282, 0.010, 0.0300),        # elephant valley
    (-1.250, 0.020, 0.0800),        # period-2 minibrot neck
    (-0.088, 0.654, 0.0400),        # spiral arm
]


def fx(v):                # real → fixed
    return round(v * S)


def views_words():
    out = []
    for cx, cy, hw in VIEWS_REAL:
        step = max(1, round((2 * hw / GW) * S))   # fixed step per cell ≥ 1
        out += [fx(cx), fx(cy), step]
    return out


def palette_words():
    """Fractint 'fire' feel: black→red→orange→yellow→white→blue and back."""
    pal = []
    for i in range(NPAL):
        t = i / NPAL
        if t < 0.4:
            r, g, b = int(255 * t / 0.4), 0, int(96 * (0.4 - t) / 0.4)
        elif t < 0.7:
            u = (t - 0.4) / 0.3
            r, g, b = 255, int(255 * u), 0
        else:
            u = (t - 0.7) / 0.3
            r, g, b = 255, 255, int(255 * u)
        pal.append((r << 16) | (g << 8) | b)
    return pal


def emit(test_mode=False, test_view=0):
    L = []
    A = L.append
    A('; mandelbrot_screensaver.t5asm — generated by gen_mandelbrot_t5asm.py')
    A('; TernOO-5500FP native Mandelbrot with Fractint-style palette cycling')
    A('main:')
    # open window
    A('    LI   R2, 512')
    A('    LI   R3, 384')
    A('    LI   R4, win_title')
    A('    LI   R1, 100        ; PIGART_OPEN_WINDOW')
    A('    SYSCALL')
    A(f'    LI   R22, {test_view}   ; view index')
    A('next_view:')
    A('    ; load view params: R23=cx R24=cy R25=step')
    A('    LI   R26, views')
    A('    MULI R27, R22, 3')
    A('    ADD  R26, R26, R27')
    A('    LDW  R23, R26, 0')
    A('    LDW  R24, R26, 1')
    A('    LDW  R25, R26, 2')
    A('    CALL compute')
    if test_mode:
        A('    ; test mode: checksum iters, print, halt')
        A('    LI   R30, 0')
        A('    LI   R18, 0')
        A('tsum:')
        A('    LI   R26, iters')
        A('    ADD  R26, R26, R30')
        A('    LDW  R27, R26, 0')
        A('    ADD  R18, R18, R27')
        A('    ADDI R30, R30, 1')
        A(f'    LI   R28, {GW*GH}')
        A('    BLT  R30, R28, tsum')
        A('    MOV  R2, R18')
        A('    LI   R1, 1          ; print number')
        A('    SYSCALL')
        A('    LI   R1, 6          ; newline')
        A('    SYSCALL')
        A('    HALT')
    A('    ; record view start time')
    A('    LI   R1, 110        ; GET_TICKS')
    A('    SYSCALL')
    A('    MOV  R21, R1')
    A('frame:')
    A('    LI   R1, 110')
    A('    SYSCALL')
    A('    MOV  R20, R1        ; now')
    A(f'    LI   R27, {PHASE_MS}')
    A('    DIV  R19, R20, R27')
    A(f'    LI   R27, {NPAL}')
    A('    MOD  R19, R19, R27  ; palette phase')
    A('    CALL draw')
    A('    LI   R1, 107        ; PRESENT')
    A('    SYSCALL')
    A('poll:')
    A('    LI   R1, 108        ; POLL_EVENT')
    A('    SYSCALL')
    A('    BEQZ R1, polled     ; 0 = no more events')
    A('    LI   R27, 1         ; EVENT_CLOSE')
    A('    BEQ  R1, R27, quit')
    A('    LI   R27, 2         ; EVENT_KEY_DOWN → quit (screensaver!)')
    A('    BEQ  R1, R27, quit')
    A('    JMP  poll')
    A('polled:')
    A('    LI   R2, 16')
    A('    LI   R1, 109        ; SLEEP_MS')
    A('    SYSCALL')
    A('    SUB  R27, R20, R21')
    A('    LI   R28, 10000')
    A(f'    MULI R28, R28, {VIEW_MS//10000}   ; VIEW_MS composed (LI caps ±29524)')
    A('    BLT  R27, R28, frame')
    A('    ADDI R22, R22, 1')
    A(f'    LI   R27, {len(VIEWS_REAL)}')
    A('    MOD  R22, R22, R27')
    A('    JMP  next_view')
    A('quit:')
    A('    LI   R1, 111        ; CLOSE_WINDOW')
    A('    SYSCALL')
    A('    HALT')
    A('')
    # ---- compute: fill iters[] for current view (R23 cx, R24 cy, R25 step)
    A('compute:')
    A('    LI   R30, 0         ; i')
    A('c_loop:')
    A(f'    LI   R27, {GW}')
    A('    MOD  R31, R30, R27  ; px')
    A('    DIV  R32, R30, R27  ; py')
    A(f'    SUBI R28, R31, {GW//2}')
    A('    MUL  R28, R28, R25')
    A('    ADD  R33, R23, R28  ; c_re')
    A(f'    SUBI R28, R32, {GH//2}')
    A('    MUL  R28, R28, R25')
    A('    ADD  R34, R24, R28  ; c_im')
    A('    LI   R35, 0         ; zx')
    A('    LI   R36, 0         ; zy')
    A('    LI   R39, 0         ; it')
    A('m_loop:')
    A('    MUL  R37, R35, R35')
    A(f'    LI   R27, {S}')
    A('    DIV  R37, R37, R27  ; zx2')
    A('    MUL  R38, R36, R36')
    A('    DIV  R38, R38, R27  ; zy2')
    A('    ADD  R28, R37, R38')
    A(f'    LI   R29, {4*S}')
    A('    BGT  R28, R29, m_done')
    A('    MUL  R28, R35, R36')
    A('    DIV  R28, R28, R27')
    A('    ADD  R28, R28, R28  ; 2*zx*zy/S')
    A('    ADD  R36, R28, R34  ; zy\'')
    A('    SUB  R28, R37, R38')
    A('    ADD  R35, R28, R33  ; zx\'')
    A('    ADDI R39, R39, 1')
    A(f'    LI   R29, {MAXIT}')
    A('    BLT  R39, R29, m_loop')
    A('m_done:')
    A('    LI   R26, iters')
    A('    ADD  R26, R26, R30')
    A('    STW  R39, R26, 0')
    A('    ADDI R30, R30, 1')
    A(f'    LI   R27, {GW*GH}')
    A('    BLT  R30, R27, c_loop')
    A('    RET')
    A('')
    # ---- draw(phase R19)
    A('draw:')
    A('    LI   R30, 0')
    A('d_loop:')
    A('    LI   R26, iters')
    A('    ADD  R26, R26, R30')
    A('    LDW  R39, R26, 0')
    A(f'    LI   R27, {MAXIT}')
    A('    BGE  R39, R27, d_next   ; interior: draw nothing (set = silhouette)')
    A('    ADD  R28, R39, R19')
    A(f'    LI   R29, {NPAL}')
    A('    MOD  R28, R28, R29')
    A('    LI   R26, palette')
    A('    ADD  R26, R26, R28')
    A('    LDW  R6, R26, 0')
    A('d_col:')
    A(f'    LI   R27, {GW}')
    A('    MOD  R2, R30, R27')
    A(f'    MULI R2, R2, {CELL}   ; x')
    A('    DIV  R3, R30, R27')
    A(f'    MULI R3, R3, {CELL}   ; y')
    A(f'    LI   R4, {CELL}')
    A(f'    LI   R5, {CELL}')
    A('    LI   R7, 1          ; filled')
    A('    LI   R1, 102        ; DRAW_RECT')
    A('    SYSCALL')
    A('d_next:')
    A('    ADDI R30, R30, 1')
    A(f'    LI   R27, {GW*GH}')
    A('    BLT  R30, R27, d_loop')
    A('    RET')
    A('')
    # ---- data
    A('win_title:')
    for ch in 'TernOO-5500FP  ::  raining trits':
        A(f'    .word {ord(ch)}')
    A('    .word 0')
    A('views:')
    for wv in views_words():
        A(f'    .word {wv}')
    A('palette:')
    for c in palette_words():
        A(f'    .word {c}')
    A('iters:')
    for _ in range(GW * GH):
        A('    .word 0')
    return '\n'.join(L) + '\n'


if __name__ == '__main__':
    out = sys.argv[1] if len(sys.argv) > 1 else 'mandelbrot_screensaver.t5asm'
    test = '--test' in sys.argv
    view = 0
    for a in sys.argv:
        if a.startswith('--view='):
            view = int(a.split('=')[1])
    open(out, 'w').write(emit(test_mode=test, test_view=view))
    print(f"wrote {out} (test_mode={test})")
