#!/usr/bin/env python3
"""gen_ghost_t5asm.py — emit GHOST's native forward pass as t5asm.

Everything runs on the 5500FP emulator: trigram hashing, feature
ternarization, both MAC layers, ReLU, argmax with margin.  No host-side
inference anywhere.  Output: two integers on stdout — class index, then
margin — which must equal ghost_train.ref_forward bit-for-bit
(test_ghost.py enforces it).

Lawful ISA: registers R8–R29 only; all immediates < ±29524; weights and
input arrive as .word data.

Usage:
    from gen_ghost_t5asm import emit_forward
    asm = emit_forward("make this loud", model_dict)

Date: 2026-07-05, Adelaide
Authors: Stevo (SkepticusMaximus) + Claude (Anthropic)
"""

from __future__ import annotations

import json
import sys


def emit_forward(text: str, model: dict) -> str:
    nfeat = model['nfeat']; nhid = model['nhid']
    ncls = len(model['classes'])
    W1, W2 = model['W1'], model['W2']
    chars = [ord(c) % 128 for c in text.lower()]

    L = []
    A = L.append
    A('; ghost_forward.t5asm — generated by gen_ghost_t5asm.py')
    A('; GHOST First Breath: native inference, no host-side math.')
    A('main:')
    # ── pass 1: trigram hash → raw feature accumulation ──────────────────
    A('    LI   R8, input       ; p')
    A('h_loop:')
    A('    LDW  R11, R8, 2      ; c2 (lookahead)')
    A('    BEQZ R11, h_done     ; NUL at i+2 → no more trigrams')
    A('    LDW  R9,  R8, 0      ; c0')
    A('    LDW  R10, R8, 1      ; c1')
    A('    MULI R12, R9, 7')
    A('    MULI R13, R10, 31')
    A('    ADD  R12, R12, R13')
    A('    MULI R13, R11, 131')
    A('    ADD  R12, R12, R13')
    A(f'    LI   R14, {nfeat}')
    A('    MOD  R12, R12, R14   ; slot')
    A('    MULI R13, R9, 17')
    A('    MULI R15, R10, 13')
    A('    ADD  R13, R13, R15')
    A('    MULI R15, R11, 11')
    A('    ADD  R13, R13, R15')
    A('    LI   R14, 2')
    A('    MOD  R13, R13, R14   ; parity')
    A('    LI   R15, 1')
    A('    BEQZ R13, h_pos')
    A('    LI   R15, -1')
    A('h_pos:')
    A('    LI   R14, feats')
    A('    ADD  R14, R14, R12')
    A('    LDW  R16, R14, 0')
    A('    ADD  R16, R16, R15')
    A('    STW  R16, R14, 0')
    A('    ADDI R8, R8, 1')
    A('    JMP  h_loop')
    A('h_done:')
    # ── pass 2: ternarize features (sign) ────────────────────────────────
    A('    LI   R8, 0')
    A('t_loop:')
    A('    LI   R14, feats')
    A('    ADD  R14, R14, R8')
    A('    LDW  R16, R14, 0')
    A('    LI   R15, 0')
    A('    BEQZ R16, t_store')
    A('    LI   R15, 1')
    A('    BGTZ R16, t_store')
    A('    LI   R15, -1')
    A('t_store:')
    A('    STW  R15, R14, 0')
    A('    ADDI R8, R8, 1')
    A(f'    LI   R14, {nfeat}')
    A('    BLT  R8, R14, t_loop')
    # ── layer 1: h[j] = ReLU(Σ f[i]·W1[i][j]) ─────────────────────────────
    A('    LI   R9, 0           ; j')
    A('l1_j:')
    A('    LI   R17, 0          ; acc')
    A('    LI   R8, 0           ; i')
    A('l1_i:')
    A('    LI   R14, feats')
    A('    ADD  R14, R14, R8')
    A('    LDW  R16, R14, 0     ; f[i]')
    A('    BEQZ R16, l1_skip')
    A(f'    MULI R14, R8, {nhid}')
    A('    ADD  R14, R14, R9')
    A('    LI   R15, w1')
    A('    ADD  R14, R14, R15')
    A('    LDW  R15, R14, 0     ; W1[i][j]')
    A('    MUL  R15, R15, R16')
    A('    ADD  R17, R17, R15')
    A('l1_skip:')
    A('    ADDI R8, R8, 1')
    A(f'    LI   R14, {nfeat}')
    A('    BLT  R8, R14, l1_i')
    A('    BGTZ R17, l1_relu')
    A('    LI   R17, 0')
    A('l1_relu:')
    A('    LI   R14, hidden')
    A('    ADD  R14, R14, R9')
    A('    STW  R17, R14, 0')
    A('    ADDI R9, R9, 1')
    A(f'    LI   R14, {nhid}')
    A('    BLT  R9, R14, l1_j')
    # ── layer 2 + streaming argmax/second ────────────────────────────────
    A('    LI   R20, -20000     ; best value')
    A('    LI   R21, -20000     ; second value')
    A('    LI   R22, 0          ; best k')
    A('    LI   R10, 0          ; k')
    A('l2_k:')
    A('    LI   R17, 0')
    A('    LI   R9, 0')
    A('l2_j:')
    A('    LI   R14, hidden')
    A('    ADD  R14, R14, R9')
    A('    LDW  R16, R14, 0')
    A('    BEQZ R16, l2_skip')
    A(f'    MULI R14, R9, {ncls}')
    A('    ADD  R14, R14, R10')
    A('    LI   R15, w2')
    A('    ADD  R14, R14, R15')
    A('    LDW  R15, R14, 0')
    A('    MUL  R15, R15, R16')
    A('    ADD  R17, R17, R15')
    A('l2_skip:')
    A('    ADDI R9, R9, 1')
    A(f'    LI   R14, {nhid}')
    A('    BLT  R9, R14, l2_j')
    A('    BLE  R17, R20, l2_notbest')
    A('    MOV  R21, R20        ; old best → second')
    A('    MOV  R20, R17')
    A('    MOV  R22, R10')
    A('    JMP  l2_next')
    A('l2_notbest:')
    A('    BLE  R17, R21, l2_next')
    A('    MOV  R21, R17')
    A('l2_next:')
    A('    ADDI R10, R10, 1')
    A(f'    LI   R14, {ncls}')
    A('    BLT  R10, R14, l2_k')
    # ── output: class index, newline, margin, newline ─────────────────────
    A('    MOV  R2, R22')
    A('    LI   R1, 1')
    A('    SYSCALL')
    A('    LI   R1, 6')
    A('    SYSCALL')
    A('    SUB  R2, R20, R21')
    A('    LI   R1, 1')
    A('    SYSCALL')
    A('    LI   R1, 6')
    A('    SYSCALL')
    A('    HALT')
    # ── data ──────────────────────────────────────────────────────────────
    A('input:')
    for c in chars:
        A(f'    .word {c}')
    A('    .word 0')
    A('    .word 0')
    A('    .word 0')
    A('feats:')
    for _ in range(nfeat):
        A('    .word 0')
    A('hidden:')
    for _ in range(nhid):
        A('    .word 0')
    A('w1:')
    for row in W1:
        for v in row:
            A(f'    .word {v}')
    A('w2:')
    for row in W2:
        for v in row:
            A(f'    .word {v}')
    return '\n'.join(L) + '\n'


if __name__ == '__main__':
    model = json.load(open('ghost_model.json'))
    text = ' '.join(sys.argv[1:]) or 'make this loud'
    sys.stdout.write(emit_forward(text, model))
