#!/usr/bin/env python3
"""
TernOO-5500FP Assembly Bridge
==============================
Emits valid 5500FP assembly (Tlang format) from a FlowCode JSON canvas.
Each FlowCode symbol becomes a labelled assembly block.
Each edge becomes a JMP/JSR instruction.
TernOO words are emitted as .word directives.

Added: 31 May 2026, Adelaide
Authors: Stevo (SkepticusMaximus) + Claude (Anthropic)
Companion: docs/TernOO-5500FP-Companion.md § Assembly Bridge
Whitepaper: Section 8 (Implementation)

Usage:
  python3 ternoo_asm_bridge.py FlowCode/AgeTest2.json
  python3 ternoo_asm_bridge.py FlowCode/AgeTest2.json --out AgeTest2.tasm

Output format: Tlang assembler source (.tasm)
  Labels:    symbol_N:          (one per FlowCode symbol)
  Words:     .word <value>      (TernOO word as signed integer)
  Jumps:     JMP symbol_N       (unconditional edge)
  Branches:  JEQ / JNE / JB    (conditional edge, trit-based)
  Comments:  ; ...              (symbol label, kind, TernOO word decode)

Status: SKELETON
  - Word emission correct (validated against emulator)
  - Jump targets correct
  - Instruction encoding placeholder (requires Tlang validation)
  - I/O channel wiring placeholder (requires hardware register map)
"""

import sys, os, json
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import importlib.util as _ilu
_spec = _ilu.spec_from_file_location(
    'ternoo_v03',
    os.path.join(os.path.dirname(os.path.abspath(__file__)),
                 '5500fp_ternoo_v03.py'))
_mod = _ilu.module_from_spec(_spec)
_spec.loader.exec_module(_mod)

build_udp_word  = _mod.build_udp_word
build_exec_word = _mod.build_exec_word
decode_word     = _mod.decode_word
describe_word   = _mod.describe_word
EXEC_PRIV_USER  = _mod.EXEC_PRIV_USER
EXEC_CALL_REGISTER = _mod.EXEC_CALL_REGISTER
EXEC_RET_DATA   = _mod.EXEC_RET_DATA


# ── Symbol kind → UDP subclass mapping ───────────────────────────────────────
# Added: 31 May 2026, Adelaide
KIND_SUBCLASS = {
    'process':    (0,   0),
    'decision':   (0,  +1),
    'io':         (+1,  0),
    'terminator': (+1, +1),
}

# ── Tlang register names ──────────────────────────────────────────────────────
# Added: 31 May 2026, Adelaide
# 5500FP has 27 registers (R0..R26 in balanced ternary addressing)
# We use a small conventional set for the bridge output:
REG_ACCUM  = 'R1'    # accumulator — eval stack top
REG_TEMP   = 'R2'    # temporary
REG_PC     = 'R3'    # program counter mirror
REG_STACK  = 'R4'    # eval stack pointer
REG_ENV    = 'R5'    # environment pointer
REG_WORD   = 'R6'    # current TernOO word


# ── Assembly emitter ──────────────────────────────────────────────────────────

class AsmEmitter:
    """
    Emits 5500FP Tlang assembly from a FlowCode JSON canvas.
    Added: 31 May 2026, Adelaide
    """

    def __init__(self, canvas: dict, source_name: str = 'flowcode'):
        self.canvas      = canvas
        self.source_name = source_name
        self.symbols     = {s['id']: s for s in canvas.get('symbols', [])}
        self.edges       = canvas.get('edges', [])
        self.lines       = []   # output lines
        self._indent     = '    '

        # Build adjacency map
        self.outgoing = {}   # src_id → [edge]
        self.incoming = {}   # dst_id → [edge]
        for e in self.edges:
            self.outgoing.setdefault(e['src'], []).append(e)
            self.incoming.setdefault(e['dst'], []).append(e)

    def _label(self, sym_id: int) -> str:
        """Generate a safe assembly label for a symbol."""
        sym = self.symbols.get(sym_id, {})
        raw = sym.get('label', f'sym_{sym_id}')
        safe = raw.upper().replace(' ', '_').replace('-', '_')
        return f"{safe}_{sym_id}"

    def _emit(self, line: str):
        self.lines.append(line)

    def _comment(self, text: str):
        self._emit(f"; {text}")

    def _instr(self, mnemonic: str, *args):
        parts = [mnemonic] + list(args)
        self._emit(f"{self._indent}{' '.join(str(a) for a in parts)}")

    def _word_directive(self, word: int):
        """Emit a TernOO word as a .word directive with decode comment."""
        d = describe_word(word)
        self._emit(f"{self._indent}.word {word}  ; {d}")

    def emit_header(self):
        """Emit file header and metadata."""
        self._comment("="*56)
        self._comment(f"TernOO-5500FP Assembly — generated by ternoo_asm_bridge.py")
        self._comment(f"Source: {self.source_name}")
        self._comment(f"Symbols: {len(self.symbols)}  Edges: {len(self.edges)}")
        self._comment("Added: 31 May 2026, Adelaide")
        self._comment("="*56)
        self._emit("")
        self._comment("Register conventions:")
        self._comment(f"  {REG_ACCUM}  = eval stack top (accumulator)")
        self._comment(f"  {REG_TEMP}  = temporary")
        self._comment(f"  {REG_STACK}  = eval stack pointer")
        self._comment(f"  {REG_ENV}  = environment pointer")
        self._comment(f"  {REG_WORD}  = current TernOO word")
        self._emit("")

    def emit_word_table(self):
        """
        Emit the TernOO word table — one UDP word per symbol,
        one EXEC word per edge, stored at program start.
        Added: 31 May 2026, Adelaide
        """
        self._comment("-"*40)
        self._comment("TernOO Word Table")
        self._comment("UDP words (symbol descriptors)")
        self._comment("-"*40)
        self._emit("word_table:")

        for sym in self.canvas.get('symbols', []):
            kind = sym.get('kind', 'process')
            t1, t0 = KIND_SUBCLASS.get(kind, (0, 0))
            udp = build_udp_word(t1, t0,
                                  sym.get('offset', 0),
                                  sym.get('code_seg', 0),
                                  sym.get('data_seg', 0))
            self._comment(f"Symbol {sym['id']}: {sym.get('label','')} [{kind}]")
            self._word_directive(udp)

        self._emit("")
        self._comment("EXEC words (edge descriptors)")
        for i, edge in enumerate(self.edges):
            exec_w = build_exec_word(
                edge.get('privilege',  EXEC_PRIV_USER),
                edge.get('call_style', EXEC_CALL_REGISTER),
                edge.get('return_type',EXEC_RET_DATA),
                edge.get('seg_idx', 0),
                edge.get('offset', 0)
            )
            cond = edge.get('condition', '')
            self._comment(f"Edge {edge['src']}→{edge['dst']}"
                          + (f" [{cond}]" if cond else ""))
            self._word_directive(exec_w)

        self._emit("")

    def emit_symbol_block(self, sym: dict):
        """
        Emit one labelled assembly block for a FlowCode symbol.
        Added: 31 May 2026, Adelaide

        Block structure:
          LABEL:
            ; kind, UDP word
            LD.W REG_WORD, #udp_word   ; load this symbol's word
            <kind-specific code>
            <jump to outgoing edge targets>
        """
        sym_id = sym['id']
        kind   = sym.get('kind', 'process')
        label  = sym.get('label', f'sym_{sym_id}')
        asm_lbl= self._label(sym_id)

        t1, t0 = KIND_SUBCLASS.get(kind, (0, 0))
        udp = build_udp_word(t1, t0,
                              sym.get('offset', 0),
                              sym.get('code_seg', 0),
                              sym.get('data_seg', 0))

        self._emit(f"{asm_lbl}:")
        self._comment(f"{kind.upper()} '{label}' — UDP: {describe_word(udp)}")
        self._instr(f"LD.W", REG_WORD, f"#{udp}")

        out_edges = self.outgoing.get(sym_id, [])

        if kind == 'terminator':
            if not self.incoming.get(sym_id):
                # START — entry point
                self._comment("START — program entry")
                self._instr("PUSHAG")      # save all registers
            else:
                # END — program exit
                self._comment("END — program exit")
                self._instr("POPAG")       # restore all registers
                self._instr("HLT")         # halt
                return                     # no outgoing jump needed

        elif kind == 'io':
            # I/O: detect read vs write from label keywords
            words = set(label.upper().replace('-',' ').replace('_',' ').split())
            write_h = {'OUTPUT','PRINT','SHOW','DISPLAY','MESSAGE','RESULT',
                       'ACCEPT','UNDER','PASS','FAIL','TELL','SAY','RESPOND'}
            if words & write_h:
                self._comment(f"I/O prompt-write: OUT to display channel")
                self._instr("OUT.W", REG_ACCUM, "#0")  # channel 0 = display
            else:
                self._comment(f"I/O prompt-read: IN from input channel")
                self._instr("IN.W",  REG_ACCUM, "#1")  # channel 1 = input
                self._comment("Result in REG_ACCUM — push to eval stack")
                self._instr("PUSH.W", REG_ACCUM)

        elif kind == 'process':
            self._comment("Process: execute code segment")
            self._instr("JSR", f"code_seg_{sym.get('code_seg', 0)}")

        elif kind == 'decision':
            self._comment("Decision: compare REG_ACCUM against zero (ternary)")
            self._comment("  JB  = branch if negative (trit = -1)")
            self._comment("  JEQ = branch if zero     (trit =  0)")
            self._comment("  >0  = fall through        (trit = +1)")
            # Decision with 2 outgoing edges
            if len(out_edges) >= 2:
                e0, e1 = out_edges[0], out_edges[1]
                cond0 = e0.get('condition','').upper()
                cond1 = e1.get('condition','').upper()
                lbl0  = self._label(e0['dst'])
                lbl1  = self._label(e1['dst'])
                # Map condition labels to branch instructions
                # Positive trit (+1) → first edge (fall through or JMP)
                # Negative trit (-1) → second edge (JB)
                self._instr("JB",  lbl1)   # negative → edge 1
                self._instr("JMP", lbl0)   # positive/zero → edge 0
                self._emit("")
                return                     # jumps already emitted
            elif len(out_edges) == 1:
                self._instr("JMP", self._label(out_edges[0]['dst']))
                self._emit("")
                return

        # Single outgoing edge — unconditional jump
        if len(out_edges) == 1:
            self._instr("JMP", self._label(out_edges[0]['dst']))
        elif len(out_edges) == 0:
            pass   # terminal node — no jump needed
        self._emit("")

    def emit_program(self):
        """Emit the full program."""
        self.emit_header()
        self.emit_word_table()

        # Find start node (terminator with no incoming, or first symbol)
        inc_ids = set(e['dst'] for e in self.edges)
        starts  = [s for s in self.canvas.get('symbols',[])
                   if s['id'] not in inc_ids]
        if not starts:
            starts = list(self.symbols.values())

        # Topological-ish order: start first, then BFS
        ordered = []
        visited = set()
        queue   = [starts[0]['id']]
        while queue:
            sid = queue.pop(0)
            if sid in visited: continue
            visited.add(sid)
            ordered.append(self.symbols[sid])
            for e in self.outgoing.get(sid, []):
                queue.append(e['dst'])
        # Add any unreachable symbols
        for sym in self.canvas.get('symbols',[]):
            if sym['id'] not in visited:
                ordered.append(sym)

        self._comment("-"*40)
        self._comment("Program blocks")
        self._comment("-"*40)
        self._emit("")

        # Emit entry jump
        self._emit(".entry")
        self._instr("JMP", self._label(ordered[0]['id']))
        self._emit("")

        for sym in ordered:
            self.emit_symbol_block(sym)

        return '\n'.join(self.lines)


# ── CLI ───────────────────────────────────────────────────────────────────────

def main():
    if len(sys.argv) < 2:
        print("Usage: python3 ternoo_asm_bridge.py <flowcode.json> [--out <file.tasm>]")
        sys.exit(1)

    in_path  = sys.argv[1]
    out_path = None
    if '--out' in sys.argv:
        idx = sys.argv.index('--out')
        if idx + 1 < len(sys.argv):
            out_path = sys.argv[idx + 1]

    with open(in_path) as f:
        canvas = json.load(f)

    source_name = os.path.basename(in_path)
    emitter = AsmEmitter(canvas, source_name)
    asm = emitter.emit_program()

    if out_path:
        with open(out_path, 'w') as f:
            f.write(asm)
        print(f"Assembly written → {out_path}")
    else:
        print(asm)


if __name__ == '__main__':
    main()
