#!/usr/bin/env python3
"""
TernOO Word Interpreter  v0.2.1
================================
Executes TernOO word programs generated by FlowCode.

The interpreter bridges the gap between:
  FlowCode (generates MAP/UDP/EXEC word sequences)
  5500FP emulator (executes raw ISA instructions)

It operates at the TernOO word level — above the ISA but below Python.
Each word is dispatched by its primary type:

  EXEC word  → follow the edge to the target symbol, call its handler
  MAP word   → record spatial position, pass to renderer if active
  DATA/UDP   → instantiate or update an object, push onto eval stack
  DATA/SCALAR→ push value onto eval stack
  NEURAL     → forward-pass through a neural unit or connection
  I/O        → read/write channel, signal START or END of program
  NULL       → Double Null mechanism — push/pop context

A FlowCode program is a directed graph of symbols (UDP words) connected
by edges (EXEC words), with MAP words encoding each symbol's canvas
position. The interpreter walks the graph from the START symbol,
dispatching each symbol's handler, following EXEC edges as control flow.

Usage:
    from ternoo_interpreter import TernOOInterpreter, load_flowcode
    interp = TernOOInterpreter()
    interp.load_flowcode('myprogram.json')
    interp.run()

Or run directly:
    python3 ternoo_interpreter.py myprogram.json
    python3 ternoo_interpreter.py --demo
"""

import sys
import os
import json
from typing import List, Dict, Optional, Callable, Any

# ── Locate and import emulator ────────────────────────────────────────────────

def _find_emulator():
    candidates = [
        os.path.join(os.path.dirname(os.path.abspath(__file__)), '5500fp_ternoo.py'),
        os.path.join(os.path.dirname(os.path.abspath(__file__)), '5500fp_ternoo_v03.py'),
        os.path.join(os.getcwd(), '5500fp_ternoo.py'),
        os.path.join(os.getcwd(), '5500fp_ternoo_v03.py'),
        os.path.expanduser('~/dev/SkepticusMaximus/TernOO-5500FP/5500fp/5500fp_ternoo.py'),
        os.path.expanduser('~/dev/SkepticusMaximus/TernOO-5500FP/5500fp/5500fp_ternoo_v03.py'),
    ]
    for p in candidates:
        if os.path.exists(p): return p
    return None

_emu_path = _find_emulator()
if _emu_path is None:
    print("ERROR: Cannot find 5500fp_ternoo.py"); sys.exit(1)

from importlib.util import spec_from_file_location, module_from_spec
import unittest.mock
_spec = spec_from_file_location("emu", _emu_path)
_emu  = module_from_spec(_spec)
with unittest.mock.patch.object(_emu, "__name__", "emu"):
    _spec.loader.exec_module(_emu)

globals().update({k: getattr(_emu,k) for k in dir(_emu) if not k.startswith('__')})

# ── Symbol kinds (must match FlowCode) ───────────────────────────────────────

SYMBOL_PROCESS  = 'process'
SYMBOL_DECISION = 'decision'
SYMBOL_IO       = 'io'

# ── Colours for trace output ──────────────────────────────────────────────────

BOLD  = '\033[1m';  RESET = '\033[0m'
CYAN  = '\033[36m'; GREEN = '\033[32m'; YELLOW = '\033[33m'
RED   = '\033[31m'; BLUE  = '\033[34m'; DIM    = '\033[2m'
MAGENTA = '\033[35m'

KIND_COLOUR = {
    SYMBOL_PROCESS:  BLUE,
    SYMBOL_DECISION: MAGENTA,
    SYMBOL_IO:       GREEN,
}

# ── FlowCode program representation ──────────────────────────────────────────

class FCNode:
    """One symbol from a FlowCode JSON canvas."""
    def __init__(self, d: dict):
        self.id       = d['id']
        self.kind     = d['kind']
        self.label    = d.get('label', f"#{d['id']}")
        self.x        = d.get('x', 0)
        self.y        = d.get('y', 0)
        self.code_seg = d.get('code_seg', 0)
        self.data_seg = d.get('data_seg', 0)
        self.offset   = d.get('offset', 0)
        self.default_output = d.get('default_output', '')
        # Runtime state
        self.visit_count = 0
        self.data_stack: List[Any] = []  # values accumulated at this node

    def to_udp_word(self) -> int:
        from_dict = {
            SYMBOL_PROCESS:  (0,  0),
            SYMBOL_DECISION: (0, +1),
            SYMBOL_IO:       (+1, 0),
        }
        t1,t0 = from_dict.get(self.kind,(0,0))
        return build_udp_word(t1, t0, self.offset, self.code_seg, self.data_seg)

    def to_map_word(self) -> int:
        cx = max(-364, min(364, self.x - 364))
        cy = max(-364, min(364, self.y - 364))
        return build_map_word(0, 1 if cx>=0 else -1, 1 if cy>=0 else -1,
                              abs(cx)*729 + abs(cy))

    def __repr__(self):
        return f"FCNode({self.kind} #{self.id} '{self.label}')"


class FCLink:
    """One edge from a FlowCode JSON canvas."""
    def __init__(self, d: dict):
        self.src_id      = d['src']
        self.dst_id      = d['dst']
        self.privilege   = d.get('privilege',   EXEC_PRIV_USER)
        self.call_style  = d.get('call_style',  EXEC_CALL_REGISTER)
        self.return_type = d.get('return_type', EXEC_RET_DATA)
        self.seg_idx     = d.get('seg_idx', 0)
        self.offset      = d.get('offset',  0)
        self.waypoints   = d.get('waypoints', [])
        # Optional condition label for decision branches
        self.condition   = d.get('condition', '')

    def to_exec_word(self) -> int:
        return build_exec_word(self.privilege, self.call_style,
                               self.return_type, self.seg_idx, self.offset)


class FCProgram:
    """A complete FlowCode program loaded from JSON."""

    def __init__(self):
        self.nodes: Dict[int, FCNode] = {}
        self.links: List[FCLink]      = []
        self._adj:  Dict[int, List[FCLink]] = {}   # adjacency: src_id → [links]
        self._radj: Dict[int, List[FCLink]] = {}   # reverse:   dst_id → [links]

    def load(self, path: str):
        with open(path) as f:
            data = json.load(f)
        self.nodes.clear(); self.links.clear()
        for d in data.get('symbols', []):
            n = FCNode(d); self.nodes[n.id] = n
        for d in data.get('edges', []):
            self.links.append(FCLink(d))
        self._build_adjacency()
        print(f"[FC] Loaded '{path}': "
              f"{len(self.nodes)} nodes, {len(self.links)} edges")

    def load_dict(self, data: dict):
        """Load directly from a dict (for embedding in tests)."""
        self.nodes.clear(); self.links.clear()
        for d in data.get('symbols', []):
            n = FCNode(d); self.nodes[n.id] = n
        for d in data.get('edges', []):
            self.links.append(FCLink(d))
        self._build_adjacency()

    def _build_adjacency(self):
        self._adj.clear(); self._radj.clear()
        for node_id in self.nodes:
            self._adj[node_id]  = []
            self._radj[node_id] = []
        for lnk in self.links:
            self._adj.setdefault(lnk.src_id, []).append(lnk)
            self._radj.setdefault(lnk.dst_id, []).append(lnk)

    def outgoing(self, node_id: int) -> List[FCLink]:
        return self._adj.get(node_id, [])

    def incoming(self, node_id: int) -> List[FCLink]:
        return self._radj.get(node_id, [])

    def find_start(self) -> Optional[FCNode]:
        """
        Find the START node: an I/O symbol with no incoming edges,
        or failing that the I/O symbol with the lowest id,
        or failing that the node with the lowest id.
        """
        io_nodes = [n for n in self.nodes.values() if n.kind == SYMBOL_IO]
        # Prefer I/O with no incoming edges
        for n in sorted(io_nodes, key=lambda x: x.id):
            if not self.incoming(n.id):
                return n
        # Fall back to first I/O
        if io_nodes:
            return min(io_nodes, key=lambda x: x.id)
        # Fall back to first node
        if self.nodes:
            return self.nodes[min(self.nodes)]
        return None

    def find_ends(self) -> List[FCNode]:
        """END nodes: I/O symbols with no outgoing edges."""
        return [n for n in self.nodes.values()
                if n.kind == SYMBOL_IO and not self.outgoing(n.id)]

    def to_word_list(self) -> List[tuple]:
        """Generate (label, word) pairs — the TernOO word program."""
        words = []
        for n in self.nodes.values():
            words.append((f"MAP #{n.id} {n.label}", n.to_map_word()))
            words.append((f"UDP #{n.id} {n.label}", n.to_udp_word()))
        for lnk in self.links:
            src = self.nodes.get(lnk.src_id)
            dst = self.nodes.get(lnk.dst_id)
            sl  = src.label if src else f"#{lnk.src_id}"
            dl  = dst.label if dst else f"#{lnk.dst_id}"
            words.append((f"EXEC {sl}→{dl}", lnk.to_exec_word()))
        return words


# ── Interpreter ───────────────────────────────────────────────────────────────

class TernOOInterpreter:
    """
    Executes a FlowCode program as a TernOO word stream.

    Execution model:
      - Program counter (pc) is a node id, not a memory address
      - Walking an EXEC edge is a function call
      - Decision nodes dispatch based on a condition function or
        the top of the eval stack
      - I/O nodes with no outgoing edges are EXIT points
      - The call stack enables subroutine-style subgraph calls
    """

    MAX_STEPS = 1000   # prevent infinite loops in cyclic graphs

    def __init__(self, trace: bool = True):
        self.trace      = trace
        self.program:   Optional[FCProgram]   = None
        self.cpu:       CPU5500FP             = CPU5500FP()
        self.eval_stack: List[Any]            = []
        self.call_stack: List[int]            = []
        self.env:        Dict[str, Any]       = {}   # variable store
        self.handlers:   Dict[str, Callable]  = {}   # label → callable
        self.step_count: int                  = 0
        self.log:        List[str]            = []
        # Register default handlers
        self._register_builtins()

    # ── Loading ───────────────────────────────────────────────────────────────

    def load_flowcode(self, path: str):
        self.program = FCProgram()
        self.program.load(path)
        self._load_words_into_cpu()

    def load_dict(self, data: dict):
        self.program = FCProgram()
        self.program.load_dict(data)
        self._load_words_into_cpu()

    def _load_words_into_cpu(self):
        """Load the word program into CPU memory for reference."""
        words = self.program.to_word_list()
        base  = 100
        self.cpu.write_cs(0, 1000)
        self.cpu.write_ds(0, 2000)
        for i, (_, w) in enumerate(words):
            self.cpu.mem_write(base + i, w)
        if self.trace:
            print(f"{DIM}[Interp] {len(words)} words loaded at CPU addr "
                  f"{base}–{base+len(words)-1}{RESET}")

    # ── Handler registration ──────────────────────────────────────────────────

    def register_handler(self, label: str, fn: Callable):
        """Register a Python callable as the handler for a named symbol."""
        self.handlers[label] = fn

    def _register_builtins(self):
        """Default handlers for common symbol labels."""
        # These are the "standard library" of FlowCode built-in behaviours.
        # Users can override by registering handlers with the same label.
        pass   # populated below via decorator pattern in tests

    # ── Execution ─────────────────────────────────────────────────────────────

    def run(self, start_node_id: Optional[int] = None) -> dict:
        """
        Execute the program. Returns a summary dict.
        """
        if not self.program:
            raise RuntimeError("No program loaded")

        # Find start node
        if start_node_id:
            start = self.program.nodes.get(start_node_id)
        else:
            start = self.program.find_start()

        if not start:
            raise RuntimeError("No start node found")

        self.eval_stack.clear()
        self.call_stack.clear()
        self.step_count = 0
        self.log.clear()
        for n in self.program.nodes.values():
            n.visit_count = 0
            n.data_stack.clear()

        self._emit(f"\n{'═'*56}")
        self._emit(f"  TernOO Interpreter  —  FlowCode Execution Trace")
        self._emit(f"{'═'*56}")
        ends   = self.program.find_ends()
        end_ids = {n.id for n in ends}
        self._emit(f"  Start: {BOLD}{start.label}{RESET}  "
                   f"({len(self.program.nodes)} nodes, "
                   f"{len(self.program.links)} edges)")
        self._emit(f"  Ends:  "
                   f"{', '.join(n.label for n in ends) or '(none)'}")
        self._emit(f"{'─'*56}\n")

        result = self._run_iterative(start, end_ids)

        self._emit(f"\n{'─'*56}")
        self._emit(f"  Steps executed: {self.step_count}")
        self._emit(f"  Eval stack:     {self.eval_stack}")
        self._emit(f"  Environment:    {self.env}")
        self._emit(f"{'═'*56}\n")

        return {
            'steps':      self.step_count,
            'eval_stack': list(self.eval_stack),
            'env':        dict(self.env),
            'log':        list(self.log),
        }

    MAX_VISITS = 50   # max times one node can be visited before loop abort

    def _run_iterative(self, start: FCNode, end_ids: set) -> Optional[str]:
        """
        Iterative graph walker — no Python recursion, handles cycles safely.
        Uses an explicit work queue instead of the call stack.
        """
        current = start

        while current is not None:
            # Step limit
            if self.step_count >= self.MAX_STEPS:
                self._emit(f"{RED}[LIMIT] Max steps ({self.MAX_STEPS}) "
                           f"reached at {current.label}{RESET}")
                return None

            # Per-node visit limit (catches infinite loops)
            current.visit_count += 1
            if current.visit_count > self.MAX_VISITS:
                self._emit(f"{RED}[LOOP] '{current.label}' visited "
                           f"{current.visit_count} times — infinite loop "
                           f"detected, stopping{RESET}")
                return None

            self.step_count += 1
            col = KIND_COLOUR.get(current.kind, RESET)

            # Emit step
            self._emit(
                f"{col}{BOLD}► {current.label}{RESET}"
                f"{col} [{current.kind}]{RESET}"
                f"{DIM}  (visit #{current.visit_count}){RESET}")
            self._emit(
                f"  {DIM}UDP: {describe_word(current.to_udp_word())}{RESET}")
            self._emit(
                f"  {DIM}MAP: {describe_map_word(current.to_map_word())}{RESET}")

            # Run handler
            self._dispatch_handler(current, 0)

            # Check for end
            if current.id in end_ids:
                self._emit(f"  {GREEN}✓ END reached: {current.label}{RESET}")
                return current.label

            # Get outgoing edges
            outgoing = self.program.outgoing(current.id)

            if not outgoing:
                self._emit(f"  {YELLOW}⚠ No outgoing edges — "
                           f"stopped at {current.label}{RESET}")
                return None

            # Choose next edge
            if current.kind == SYMBOL_DECISION:
                chosen = self._decision_dispatch(current, outgoing, 0)
            else:
                chosen = outgoing[0] if outgoing else None

            if not chosen:
                self._emit(f"  {YELLOW}⚠ No edge chosen from "
                           f"{current.label}{RESET}")
                return None

            # Emit edge traversal
            dst = self.program.nodes.get(chosen.dst_id)
            if not dst:
                self._emit(f"  {RED}✗ Dead edge → "
                           f"#{chosen.dst_id}{RESET}")
                return None

            exec_desc = describe_word(chosen.to_exec_word())
            call = {EXEC_CALL_STACK:'stack',
                    EXEC_CALL_REGISTER:'register',
                    EXEC_CALL_MESSAGE:'message'}.get(chosen.call_style,'?')
            arrow = {'stack':'══►','register':'──→','message':'╌╌→'}.get(call,'──→')
            cond_str = f"  [{chosen.condition}]" if chosen.condition else ""
            self._emit(f"  {CYAN}{arrow} {dst.label}"
                       f"{cond_str}{RESET}"
                       f"  {DIM}EXEC: {exec_desc}{RESET}")

            # Stack call tracking
            if chosen.call_style == EXEC_CALL_STACK:
                self.call_stack.append(chosen.src_id)

            current = dst

        return None

    def _execute_node(self, node: FCNode, end_ids: set,
                      depth: int) -> Optional[str]:
        """Legacy recursive method — kept for compatibility, delegates to iterative."""
        return self._run_iterative(node, end_ids)

    def _decision_dispatch(self, node: FCNode,
                           outgoing: List[FCLink],
                           depth: int) -> Optional[FCLink]:
        """
        Choose which outgoing edge to follow from a Decision node.

        Priority:
        1. If a handler is registered for this node, call it and use
           its return value to select edge by condition label or index.
        2. If there are exactly 2 outgoing edges and the eval stack has
           a truthy value, use that for True/False branching.
        3. If there's only one outgoing edge, follow it.
        4. Otherwise follow the first edge and warn.
        """
        indent = "  " * depth

        # Handler-driven dispatch
        if node.label in self.handlers:
            try:
                # Unified signature: (node, outgoing, stack, env)
                choice = self.handlers[node.label](
                    node, outgoing, self.eval_stack, self.env)
                if isinstance(choice, int) and 0 <= choice < len(outgoing):
                    self._emit(f"{indent}  {YELLOW}◈ Decision "
                               f"'{node.label}' → branch {choice} "
                               f"(handler){RESET}")
                    return outgoing[choice]
                elif isinstance(choice, str):
                    for lnk in outgoing:
                        if lnk.condition == choice:
                            self._emit(f"{indent}  {YELLOW}◈ Decision "
                                       f"'{node.label}' → '{choice}' "
                                       f"(handler){RESET}")
                            return lnk
            except Exception as e:
                self._emit(f"{indent}  {RED}Handler error: {e}{RESET}")

        # Stack-driven True/False
        if len(outgoing) == 2 and self.eval_stack:
            val = self.eval_stack[-1]
            # Edge 0 = True/positive, Edge 1 = False/negative
            # (ternary natural: +1=true, 0=maybe, -1=false)
            if val > 0:
                idx = 0; branch = "TRUE (+)"
            elif val == 0:
                idx = 0; branch = "MAYBE (0) → TRUE path"
            else:
                idx = 1; branch = "FALSE (−)"
            self._emit(f"{indent}  {YELLOW}◈ Decision '{node.label}' "
                       f"stack={val} → {branch}{RESET}")
            return outgoing[idx]

        # Single outgoing — follow it
        if len(outgoing) == 1:
            return outgoing[0]

        # default_output on the node itself — push and match
        if hasattr(node, 'default_output') and node.default_output:
            val = node.default_output
            for lnk in outgoing:
                if lnk.condition.upper() == val.upper():
                    self._emit(f"{indent}  {YELLOW}◈ Decision "
                               f"'{node.label}' default='{val}' → "
                               f"'{lnk.condition}'{RESET}")
                    return lnk
            self._emit(f"{indent}  {YELLOW}◈ Decision '{node.label}' "
                       f"default='{val}' — no matching edge condition, "
                       f"following first{RESET}")
            return outgoing[0]

        # Multiple edges, no handler, no stack value — follow first, warn
        self._emit(f"{indent}  {YELLOW}⚠ Decision '{node.label}' has "
                   f"{len(outgoing)} edges but no condition — "
                   f"following first{RESET}")
        return outgoing[0] if outgoing else None

    def _dispatch_handler(self, node: FCNode, depth: int) -> Any:
        """Run the Python handler for this node if registered.
        Handler signature: (node, outgoing, stack, env) → value or None
        """
        indent = "  " * depth
        if node.label in self.handlers:
            outgoing = self.program.outgoing(node.id)
            try:
                result = self.handlers[node.label](
                    node, outgoing, self.eval_stack, self.env)
                if result is not None:
                    self.eval_stack.append(result)
                    self._emit(f"{indent}  {GREEN}handler → {result}{RESET}")
                return result
            except Exception as e:
                self._emit(f"{indent}  {RED}Handler error '{node.label}': "
                           f"{e}{RESET}")
        return None

    # ── Helpers ───────────────────────────────────────────────────────────────

    def _emit(self, msg: str):
        self.log.append(msg)
        if self.trace:
            print(msg)

    def set_env(self, key: str, value: Any):
        self.env[key] = value

    def push(self, value: Any):
        self.eval_stack.append(value)

    def pop(self) -> Any:
        return self.eval_stack.pop() if self.eval_stack else None


def describe_map_word(w: int) -> str:
    """Compact MAP word description for trace output."""
    try:
        d = decode_map_word(w)
        return f"{d['mode']} {d['coords']}"
    except Exception:
        return word_to_str(w)


# ── Demo programs ─────────────────────────────────────────────────────────────

def demo_linear():
    """Linear program: START → PROCESS → PROCESS → END"""
    print(f"\n{'='*56}")
    print("DEMO 1: Linear execution")
    print(f"{'='*56}")

    data = {
        'symbols': [
            {'id':1,'kind':'io',      'x':200,'y':80,  'label':'START'},
            {'id':2,'kind':'process', 'x':200,'y':200, 'label':'INIT'},
            {'id':3,'kind':'process', 'x':200,'y':320, 'label':'COMPUTE'},
            {'id':4,'kind':'io',      'x':200,'y':440, 'label':'END'},
        ],
        'edges': [
            {'src':1,'dst':2},
            {'src':2,'dst':3},
            {'src':3,'dst':4},
        ]
    }

    interp = TernOOInterpreter(trace=True)
    interp.register_handler('INIT',
        lambda n,out,stack,env: env.update({'x':42}) or print(
            f"    [INIT] env.x = 42"))
    interp.register_handler('COMPUTE',
        lambda n,out,stack,env: stack.append(env.get('x',0)*2) or print(
            f"    [COMPUTE] x*2 = {env.get('x',0)*2}"))
    interp.load_dict(data)
    result = interp.run()
    print(f"\nResult: steps={result['steps']} "
          f"stack={result['eval_stack']} env={result['env']}")


def demo_decision():
    """Decision branch: START → CHECK → (TRUE:PASS | FALSE:FAIL) → END"""
    print(f"\n{'='*56}")
    print("DEMO 2: Decision branching (ternary True/False/Maybe)")
    print(f"{'='*56}")

    data = {
        'symbols': [
            {'id':1,'kind':'io',       'x':200,'y':80,  'label':'START'},
            {'id':2,'kind':'decision', 'x':200,'y':200, 'label':'IS_POSITIVE'},
            {'id':3,'kind':'process',  'x':120,'y':320, 'label':'PASS'},
            {'id':4,'kind':'process',  'x':280,'y':320, 'label':'FAIL'},
            {'id':5,'kind':'io',       'x':200,'y':440, 'label':'END'},
        ],
        'edges': [
            {'src':1,'dst':2},
            {'src':2,'dst':3,'condition':'TRUE'},
            {'src':2,'dst':4,'condition':'FALSE'},
            {'src':3,'dst':5},
            {'src':4,'dst':5},
        ]
    }

    interp = TernOOInterpreter(trace=True)

    # Push a test value onto the stack before the decision
    interp.register_handler('START',
        lambda n,out,stack,env: stack.append(+1) or print(
            f"    [START] pushed +1 (positive/true) onto eval stack"))
    interp.register_handler('PASS',
        lambda n,out,stack,env: print(f"    [PASS] ✓ Condition was true"))
    interp.register_handler('FAIL',
        lambda n,out,stack,env: print(f"    [FAIL] ✗ Condition was false"))

    interp.load_dict(data)
    result = interp.run()
    print(f"\nResult: steps={result['steps']}")

    # Now test with negative value
    print(f"\n--- Re-run with −1 (negative/false) ---")
    interp2 = TernOOInterpreter(trace=True)
    interp2.register_handler('START',
        lambda n,out,stack,env: stack.append(-1) or print(
            f"    [START] pushed −1 (negative/false) onto eval stack"))
    interp2.register_handler('PASS',
        lambda n,out,stack,env: print(f"    [PASS] ✓ Condition was true"))
    interp2.register_handler('FAIL',
        lambda n,out,stack,env: print(f"    [FAIL] ✗ Condition was false"))
    interp2.load_dict(data)
    result2 = interp2.run()
    print(f"\nResult: steps={result2['steps']}")


def demo_loop():
    """Loop: count from 0 to 3 using a cyclic graph."""
    print(f"\n{'='*56}")
    print("DEMO 3: Loop (counter 0→3)")
    print(f"{'='*56}")

    data = {
        'symbols': [
            {'id':1,'kind':'io',       'x':200,'y':80,  'label':'START'},
            {'id':2,'kind':'process',  'x':200,'y':200, 'label':'INCREMENT'},
            {'id':3,'kind':'decision', 'x':200,'y':320, 'label':'DONE?'},
            {'id':4,'kind':'io',       'x':200,'y':440, 'label':'END'},
        ],
        'edges': [
            {'src':1,'dst':2},
            {'src':2,'dst':3},
            {'src':3,'dst':2,'condition':'FALSE'},   # loop back
            {'src':3,'dst':4,'condition':'TRUE'},    # exit
        ]
    }

    interp = TernOOInterpreter(trace=True)
    interp.set_env('counter', 0)
    interp.set_env('limit',   3)

    def increment(n, out, stack, env):
        env['counter'] += 1
        print(f"    [INCREMENT] counter = {env['counter']}")
        return env['counter']

    def done_check(n, outgoing, stack, env):
        """Decision handler signature: (node, outgoing_list, stack, env)"""
        val = env['counter'] >= env['limit']
        result = +1 if val else -1
        print(f"    [DONE?] counter={env['counter']} "
              f"limit={env['limit']} → {'DONE (+)' if val else 'CONTINUE (−)'}")
        stack.append(result)
        # Return edge index: 0=first outgoing (FALSE=loop back), 1=second (TRUE=exit)
        # edges are: [0]=FALSE(loop), [1]=TRUE(exit)
        return 1 if val else 0

    interp.register_handler('INCREMENT', increment)
    # Decision handlers take (node, outgoing_list, stack, env)
    interp.handlers['DONE?'] = done_check

    interp.load_dict(data)
    result = interp.run()
    print(f"\nResult: steps={result['steps']} "
          f"counter={result['env']['counter']}")


def demo_from_file(path: str):
    """Load and run a FlowCode JSON file."""
    print(f"\n{'='*56}")
    print(f"Running FlowCode program: {path}")
    print(f"{'='*56}")
    interp = TernOOInterpreter(trace=True)
    interp.load_flowcode(path)
    result = interp.run()
    print(f"\nSteps: {result['steps']}")
    return result


# ── Entry point ───────────────────────────────────────────────────────────────

if __name__ == '__main__':
    if '--demo' in sys.argv or len(sys.argv) == 1:
        demo_linear()
        demo_decision()
        demo_loop()
        print(f"\n{'═'*56}")
        print("All demos complete.")
        print(f"{'═'*56}")
    elif len(sys.argv) >= 2 and sys.argv[1].endswith('.json'):
        demo_from_file(sys.argv[1])
    else:
        print(__doc__)
