#!/usr/bin/env python3
"""
TernOO Word Interpreter  v0.3.0
================================
Executes TernOO word programs generated by FlowCode.

The interpreter bridges the gap between:
  FlowCode (generates MAP/UDP/EXEC word sequences)
  5500FP emulator (executes raw ISA instructions)

It operates at the TernOO word level — above the ISA but below Python.
Each word is dispatched by its primary type:

  EXEC word  → follow the edge to the target symbol, call its handler
  MAP word   → record spatial position, pass to renderer if active
  DATA/UDP   → instantiate or update an object, push onto eval stack
  DATA/SCALAR→ push value onto eval stack
  NEURAL     → forward-pass through a neural unit or connection
  I/O        → read/write channel, signal START or END of program
  NULL       → Double Null mechanism — push/pop context

A FlowCode program is a directed graph of symbols (UDP words) connected
by edges (EXEC words), with MAP words encoding each symbol's canvas
position. The interpreter walks the graph from the START symbol,
dispatching each symbol's handler, following EXEC edges as control flow.

Usage:
    from ternoo_interpreter import TernOOInterpreter, load_flowcode
    interp = TernOOInterpreter()
    interp.load_flowcode('myprogram.json')
    interp.run()

Or run directly:
    python3 ternoo_interpreter.py myprogram.json
    python3 ternoo_interpreter.py --demo
"""

import sys
import os
import json
from typing import List, Dict, Optional, Callable, Any

# ── Locate and import emulator ────────────────────────────────────────────────

def _find_emulator():
    candidates = [
        os.path.join(os.path.dirname(os.path.abspath(__file__)), '5500fp_ternoo.py'),
        os.path.join(os.path.dirname(os.path.abspath(__file__)), '5500fp_ternoo_v03.py'),
        os.path.join(os.getcwd(), '5500fp_ternoo.py'),
        os.path.join(os.getcwd(), '5500fp_ternoo_v03.py'),
        os.path.expanduser('~/dev/SkepticusMaximus/TernOO-5500FP/5500fp/5500fp_ternoo.py'),
        os.path.expanduser('~/dev/SkepticusMaximus/TernOO-5500FP/5500fp/5500fp_ternoo_v03.py'),
    ]
    for p in candidates:
        if os.path.exists(p): return p
    return None

_emu_path = _find_emulator()
if _emu_path is None:
    print("ERROR: Cannot find 5500fp_ternoo.py"); sys.exit(1)

from importlib.util import spec_from_file_location, module_from_spec
import unittest.mock
_spec = spec_from_file_location("emu", _emu_path)
_emu  = module_from_spec(_spec)
with unittest.mock.patch.object(_emu, "__name__", "emu"):
    _spec.loader.exec_module(_emu)

globals().update({k: getattr(_emu,k) for k in dir(_emu) if not k.startswith('__')})

# ── Symbol kinds (must match FlowCode) ───────────────────────────────────────

SYMBOL_PROCESS  = 'process'
SYMBOL_DECISION = 'decision'
SYMBOL_IO         = 'io'
SYMBOL_TERMINATOR = 'terminator'
SYMBOL_TERMINAL_KINDS = {SYMBOL_IO, SYMBOL_TERMINATOR}

# ── I/O Subclass Matrix ──────────────────────────────────────────────────
# Added: 31 May 2026, Adelaide | Author: Stevo + Claude
# T21: -1=file  0=stream  +1=prompt | T20: -1=read  0=bidir  +1=write
IO_CH_FILE, IO_CH_STREAM, IO_CH_PROMPT = -1, 0, +1
IO_OP_READ, IO_OP_BIDIR,  IO_OP_WRITE  = -1, 0, +1

def io_subclass(node) -> tuple:
    """Detect (T21,T20) from label keywords. Bootstrap until palette exposes trits."""
    words = set(node.label.upper().replace('-',' ').replace('_',' ').split())
    write_h = {'OUTPUT','PRINT','SHOW','DISPLAY','MESSAGE','RESULT',
               'ACCEPT','UNDER','PASS','FAIL','TELL','SAY','RESPOND'}
    read_h  = {'INPUT','GET','READ','PROMPT','ASK','ENTER','FETCH'}
    file_h  = {'FILE','LOAD','SAVE','OPEN','WRITE','APPEND','LOG'}
    stream_h= {'SEND','RECV','RECEIVE','NETWORK','STREAM','PIPE'}
    ch = IO_CH_PROMPT
    op = IO_OP_READ
    if words & file_h:    ch = IO_CH_FILE
    elif words & stream_h: ch = IO_CH_STREAM
    if words & write_h:   op = IO_OP_WRITE
    elif words & read_h:  op = IO_OP_READ
    return ch, op

# ── Colours for trace output ──────────────────────────────────────────────────

BOLD  = '\033[1m';  RESET = '\033[0m'
CYAN  = '\033[36m'; GREEN = '\033[32m'; YELLOW = '\033[33m'
RED   = '\033[31m'; BLUE  = '\033[34m'; DIM    = '\033[2m'
MAGENTA = '\033[35m'

KIND_COLOUR = {
    SYMBOL_PROCESS:    BLUE,
    SYMBOL_DECISION:   MAGENTA,
    SYMBOL_IO:         GREEN,
    SYMBOL_TERMINATOR: GREEN,
}

# ── FlowCode program representation ──────────────────────────────────────────

class FCNode:
    """One symbol from a FlowCode JSON canvas."""
    def __init__(self, d: dict):
        self.id       = d['id']
        self.kind     = d['kind']
        self.label    = d.get('label', f"#{d['id']}")
        self.x        = d.get('x', 0)
        self.y        = d.get('y', 0)
        self.code_seg = d.get('code_seg', 0)
        self.data_seg = d.get('data_seg', 0)
        self.offset   = d.get('offset', 0)
        self.default_output = d.get('default_output', '')
        # Runtime state
        self.visit_count = 0
        self.data_stack: List[Any] = []  # values accumulated at this node

    def to_udp_word(self) -> int:
        from_dict = {
            SYMBOL_PROCESS:    (0,   0),
            SYMBOL_DECISION:   (0,  +1),
            SYMBOL_IO:         (+1,  0),
            SYMBOL_TERMINATOR: (+1, +1),
        }
        t1,t0 = from_dict.get(self.kind,(0,0))
        return build_udp_word(t1, t0, self.offset, self.code_seg, self.data_seg)

    def to_map_word(self) -> int:
        cx = max(-364, min(364, self.x - 364))
        cy = max(-364, min(364, self.y - 364))
        return build_map_word(0, 1 if cx>=0 else -1, 1 if cy>=0 else -1,
                              abs(cx)*729 + abs(cy))

    def __repr__(self):
        return f"FCNode({self.kind} #{self.id} '{self.label}')"


class FCLink:
    """One edge from a FlowCode JSON canvas."""
    def __init__(self, d: dict):
        self.src_id      = d['src']
        self.dst_id      = d['dst']
        self.privilege   = d.get('privilege',   EXEC_PRIV_USER)
        self.call_style  = d.get('call_style',  EXEC_CALL_REGISTER)
        self.return_type = d.get('return_type', EXEC_RET_DATA)
        self.seg_idx     = d.get('seg_idx', 0)
        self.offset      = d.get('offset',  0)
        self.waypoints   = d.get('waypoints', [])
        # Optional condition label for decision branches
        self.condition   = d.get('condition', '')

    def to_exec_word(self) -> int:
        return build_exec_word(self.privilege, self.call_style,
                               self.return_type, self.seg_idx, self.offset)


class FCProgram:
    """A complete FlowCode program loaded from JSON."""

    def __init__(self):
        self.nodes: Dict[int, FCNode] = {}
        self.links: List[FCLink]      = []
        self._adj:  Dict[int, List[FCLink]] = {}   # adjacency: src_id → [links]
        self._radj: Dict[int, List[FCLink]] = {}   # reverse:   dst_id → [links]

    def load(self, path: str):
        with open(path) as f:
            data = json.load(f)
        self.nodes.clear(); self.links.clear()
        for d in data.get('symbols', []):
            n = FCNode(d); self.nodes[n.id] = n
        for d in data.get('edges', []):
            self.links.append(FCLink(d))
        self._build_adjacency()
        print(f"[FC] Loaded '{path}': "
              f"{len(self.nodes)} nodes, {len(self.links)} edges")

    def load_dict(self, data: dict):
        """Load directly from a dict (for embedding in tests)."""
        self.nodes.clear(); self.links.clear()
        for d in data.get('symbols', []):
            n = FCNode(d); self.nodes[n.id] = n
        for d in data.get('edges', []):
            self.links.append(FCLink(d))
        self._build_adjacency()

    def _build_adjacency(self):
        self._adj.clear(); self._radj.clear()
        for node_id in self.nodes:
            self._adj[node_id]  = []
            self._radj[node_id] = []
        for lnk in self.links:
            self._adj.setdefault(lnk.src_id, []).append(lnk)
            self._radj.setdefault(lnk.dst_id, []).append(lnk)

    def outgoing(self, node_id: int) -> List[FCLink]:
        return self._adj.get(node_id, [])

    def incoming(self, node_id: int) -> List[FCLink]:
        return self._radj.get(node_id, [])

    def find_start(self) -> Optional[FCNode]:
        """
        Find the START node: an I/O symbol with no incoming edges,
        or failing that the I/O symbol with the lowest id,
        or failing that the node with the lowest id.
        """
        terminal_nodes = [n for n in self.nodes.values()
                          if n.kind in SYMBOL_TERMINAL_KINDS]
        # Prefer Terminator with no incoming edges
        for n in sorted(terminal_nodes, key=lambda x: x.id):
            if n.kind == SYMBOL_TERMINATOR and not self.incoming(n.id):
                return n
        # Then I/O with no incoming
        for n in sorted(terminal_nodes, key=lambda x: x.id):
            if n.kind == SYMBOL_IO and not self.incoming(n.id):
                return n
        if terminal_nodes:
            return min(terminal_nodes, key=lambda x: x.id)
        # Fall back to first node
        if self.nodes:
            return self.nodes[min(self.nodes)]
        return None

    def find_ends(self) -> List[FCNode]:
        """END nodes: I/O symbols with no outgoing edges."""
        return [n for n in self.nodes.values()
                if n.kind in SYMBOL_TERMINAL_KINDS and not self.outgoing(n.id)]

    def to_word_list(self) -> List[tuple]:
        """Generate (label, word) pairs — the TernOO word program."""
        words = []
        for n in self.nodes.values():
            words.append((f"MAP #{n.id} {n.label}", n.to_map_word()))
            words.append((f"UDP #{n.id} {n.label}", n.to_udp_word()))
        for lnk in self.links:
            src = self.nodes.get(lnk.src_id)
            dst = self.nodes.get(lnk.dst_id)
            sl  = src.label if src else f"#{lnk.src_id}"
            dl  = dst.label if dst else f"#{lnk.dst_id}"
            words.append((f"EXEC {sl}→{dl}", lnk.to_exec_word()))
        return words


# ── Interpreter ───────────────────────────────────────────────────────────────

class TernOOInterpreter:
    """
    Executes a FlowCode program as a TernOO word stream.

    Execution model:
      - Program counter (pc) is a node id, not a memory address
      - Walking an EXEC edge is a function call
      - Decision nodes dispatch based on a condition function or
        the top of the eval stack
      - I/O nodes with no outgoing edges are EXIT points
      - The call stack enables subroutine-style subgraph calls
    """

    MAX_STEPS = 1000   # prevent infinite loops in cyclic graphs

    def __init__(self, trace: bool = True, tk_parent=None):
        self.trace      = trace
        self.tk_parent  = tk_parent
        self.program:   Optional[FCProgram]   = None
        self.cpu:       CPU5500FP             = CPU5500FP()
        self.eval_stack: List[Any]            = []
        self.call_stack: List[int]            = []
        self.env:        Dict[str, Any]       = {}
        self.handlers:   Dict[str, Callable]  = {}
        self.step_count: int                  = 0
        self.log:        List[str]            = []
        self._register_builtins()

    # ── Loading ───────────────────────────────────────────────────────────────

    def load_flowcode(self, path: str):
        self.program = FCProgram()
        self.program.load(path)
        self._load_words_into_cpu()

    def load_dict(self, data: dict):
        self.program = FCProgram()
        self.program.load_dict(data)
        self._load_words_into_cpu()

    def _load_words_into_cpu(self):
        """Load the word program into CPU memory for reference."""
        words = self.program.to_word_list()
        base  = 100
        self.cpu.write_cs(0, 1000)
        self.cpu.write_ds(0, 2000)
        for i, (_, w) in enumerate(words):
            self.cpu.mem_write(base + i, w)
        if self.trace:
            print(f"{DIM}[Interp] {len(words)} words loaded at CPU addr "
                  f"{base}–{base+len(words)-1}{RESET}")

    # ── Handler registration ──────────────────────────────────────────────────

    def register_handler(self, label: str, fn: Callable):
        """Register a Python callable as the handler for a named symbol."""
        self.handlers[label] = fn

    def _register_builtins(self):
        """Wire I/O subclass dispatch. Added: 31 May 2026, Adelaide."""
        self._io_kind_dispatch = True

    # ── Execution ─────────────────────────────────────────────────────────────

    def run(self, start_node_id: Optional[int] = None) -> dict:
        """
        Execute the program. Returns a summary dict.
        """
        if not self.program:
            raise RuntimeError("No program loaded")

        # Find start node
        if start_node_id:
            start = self.program.nodes.get(start_node_id)
        else:
            start = self.program.find_start()

        if not start:
            raise RuntimeError("No start node found")

        self.eval_stack.clear()
        self.call_stack.clear()
        self.step_count = 0
        self.log.clear()
        for n in self.program.nodes.values():
            n.visit_count = 0
            n.data_stack.clear()

        self._emit(f"\n{'═'*56}")
        self._emit(f"  TernOO Interpreter  —  FlowCode Execution Trace")
        self._emit(f"{'═'*56}")
        ends   = self.program.find_ends()
        end_ids = {n.id for n in ends}
        self._emit(f"  Start: {BOLD}{start.label}{RESET}  "
                   f"({len(self.program.nodes)} nodes, "
                   f"{len(self.program.links)} edges)")
        self._emit(f"  Ends:  "
                   f"{', '.join(n.label for n in ends) or '(none)'}")
        self._emit(f"{'─'*56}\n")

        result = self._run_iterative(start, end_ids)

        self._emit(f"\n{'─'*56}")
        self._emit(f"  Steps executed: {self.step_count}")
        self._emit(f"  Eval stack:     {self.eval_stack}")
        self._emit(f"  Environment:    {self.env}")
        self._emit(f"{'═'*56}\n")

        return {
            'steps':      self.step_count,
            'eval_stack': list(self.eval_stack),
            'env':        dict(self.env),
            'log':        list(self.log),
        }

    MAX_VISITS = 50   # max times one node can be visited before loop abort

    def _run_iterative(self, start: FCNode, end_ids: set) -> Optional[str]:
        """
        Iterative graph walker — no Python recursion, handles cycles safely.
        Uses an explicit work queue instead of the call stack.
        """
        current = start

        while current is not None:
            # Step limit
            if self.step_count >= self.MAX_STEPS:
                self._emit(f"{RED}[LIMIT] Max steps ({self.MAX_STEPS}) "
                           f"reached at {current.label}{RESET}")
                return None

            # Per-node visit limit (catches infinite loops)
            current.visit_count += 1
            if current.visit_count > self.MAX_VISITS:
                self._emit(f"{RED}[LOOP] '{current.label}' visited "
                           f"{current.visit_count} times — infinite loop "
                           f"detected, stopping{RESET}")
                return None

            self.step_count += 1
            col = KIND_COLOUR.get(current.kind, RESET)

            # Emit step
            self._emit(
                f"{col}{BOLD}► {current.label}{RESET}"
                f"{col} [{current.kind}]{RESET}"
                f"{DIM}  (visit #{current.visit_count}){RESET}")
            self._emit(
                f"  {DIM}UDP: {describe_word(current.to_udp_word())}{RESET}")
            self._emit(
                f"  {DIM}MAP: {describe_map_word(current.to_map_word())}{RESET}")

            # Run handler
            self._dispatch_handler(current, 0)

            # Check for end
            if current.id in end_ids:
                self._emit(f"  {GREEN}✓ END reached: {current.label}{RESET}")
                return current.label

            # Get outgoing edges
            outgoing = self.program.outgoing(current.id)

            if not outgoing:
                self._emit(f"  {YELLOW}⚠ No outgoing edges — "
                           f"stopped at {current.label}{RESET}")
                return None

            # Choose next edge
            if current.kind == SYMBOL_DECISION:
                chosen = self._decision_dispatch(current, outgoing, 0)
            else:
                chosen = outgoing[0] if outgoing else None

            if not chosen:
                self._emit(f"  {YELLOW}⚠ No edge chosen from "
                           f"{current.label}{RESET}")
                return None

            # Emit edge traversal
            dst = self.program.nodes.get(chosen.dst_id)
            if not dst:
                self._emit(f"  {RED}✗ Dead edge → "
                           f"#{chosen.dst_id}{RESET}")
                return None

            exec_desc = describe_word(chosen.to_exec_word())
            call = {EXEC_CALL_STACK:'stack',
                    EXEC_CALL_REGISTER:'register',
                    EXEC_CALL_MESSAGE:'message'}.get(chosen.call_style,'?')
            arrow = {'stack':'══►','register':'──→','message':'╌╌→'}.get(call,'──→')
            cond_str = f"  [{chosen.condition}]" if chosen.condition else ""
            self._emit(f"  {CYAN}{arrow} {dst.label}"
                       f"{cond_str}{RESET}"
                       f"  {DIM}EXEC: {exec_desc}{RESET}")

            # Stack call tracking
            if chosen.call_style == EXEC_CALL_STACK:
                self.call_stack.append(chosen.src_id)

            current = dst

        return None

    def _execute_node(self, node: FCNode, end_ids: set,
                      depth: int) -> Optional[str]:
        """Legacy recursive method — kept for compatibility, delegates to iterative."""
        return self._run_iterative(node, end_ids)

    def _decision_dispatch(self, node: FCNode,
                           outgoing: List[FCLink],
                           depth: int) -> Optional[FCLink]:
        """
        Choose which outgoing edge to follow from a Decision node.

        Priority:
        1. If a handler is registered for this node, call it and use
           its return value to select edge by condition label or index.
        2. If there are exactly 2 outgoing edges and the eval stack has
           a truthy value, use that for True/False branching.
        3. If there's only one outgoing edge, follow it.
        4. Otherwise follow the first edge and warn.
        """
        indent = "  " * depth

        # Handler-driven dispatch
        if node.label in self.handlers:
            try:
                # Unified signature: (node, outgoing, stack, env)
                choice = self.handlers[node.label](
                    node, outgoing, self.eval_stack, self.env)
                if isinstance(choice, int) and 0 <= choice < len(outgoing):
                    self._emit(f"{indent}  {YELLOW}◈ Decision "
                               f"'{node.label}' → branch {choice} "
                               f"(handler){RESET}")
                    return outgoing[choice]
                elif isinstance(choice, str):
                    for lnk in outgoing:
                        if lnk.condition == choice:
                            self._emit(f"{indent}  {YELLOW}◈ Decision "
                                       f"'{node.label}' → '{choice}' "
                                       f"(handler){RESET}")
                            return lnk
            except Exception as e:
                self._emit(f"{indent}  {RED}Handler error: {e}{RESET}")

        # Stack-driven dispatch — condition label or True/False
        if self.eval_stack and outgoing:
            val = self.eval_stack[-1]
            if isinstance(val, str):
                for lnk in outgoing:
                    if lnk.condition.upper() == val.upper():
                        self._emit(f"{indent}  {YELLOW}◈ Decision "
                                   f"'{node.label}' stack='{val}' → "
                                   f"'{lnk.condition}' (label match){RESET}")
                        return lnk
        # Full ternary dispatch — 3 outgoing edges map to all three trits
        # Edge 0 = positive (+1), Edge 1 = negative (-1), Edge 2 = zero (0)
        if len(outgoing) == 3 and self.eval_stack:
            val = self.eval_stack[-1]
            if val > 0:
                idx = 0; branch = "POSITIVE (+1)"
            elif val < 0:
                idx = 1; branch = "NEGATIVE (−1)"
            else:
                idx = 2; branch = "ZERO (0)"
            self._emit(f"{indent}  {YELLOW}◈ Decision '{node.label}' "
                       f"stack={val} → {branch}{RESET}")
            return outgoing[idx]

        if len(outgoing) == 2 and self.eval_stack:
            val = self.eval_stack[-1]
            # Edge 0 = True/positive, Edge 1 = False/negative
            # (ternary natural: +1=true, 0=maybe, -1=false)
            if val > 0:
                idx = 0; branch = "TRUE (+)"
            elif val == 0:
                idx = 0; branch = "MAYBE (0) → TRUE path"
            else:
                idx = 1; branch = "FALSE (−)"
            self._emit(f"{indent}  {YELLOW}◈ Decision '{node.label}' "
                       f"stack={val} → {branch}{RESET}")
            return outgoing[idx]

        # Single outgoing — follow it
        if len(outgoing) == 1:
            return outgoing[0]

        # default_output on the node itself — push and match
        if hasattr(node, 'default_output') and node.default_output:
            val = node.default_output
            for lnk in outgoing:
                if lnk.condition.upper() == val.upper():
                    self._emit(f"{indent}  {YELLOW}◈ Decision "
                               f"'{node.label}' default='{val}' → "
                               f"'{lnk.condition}'{RESET}")
                    return lnk
            self._emit(f"{indent}  {YELLOW}◈ Decision '{node.label}' "
                       f"default='{val}' — no matching edge condition, "
                       f"following first{RESET}")
            return outgoing[0]

        # Multiple edges, no handler, no stack value — follow first, warn
        self._emit(f"{indent}  {YELLOW}⚠ Decision '{node.label}' has "
                   f"{len(outgoing)} edges but no condition — "
                   f"following first{RESET}")
        return outgoing[0] if outgoing else None

    def _dispatch_handler(self, node: FCNode, depth: int) -> Any:
        """Run the Python handler for this node if registered.
        Handler signature: (node, outgoing, stack, env) → value or None
        """
        indent = "  " * depth
        if node.label in self.handlers:
            outgoing = self.program.outgoing(node.id)
            try:
                result = self.handlers[node.label](
                    node, outgoing, self.eval_stack, self.env)
                if result is not None:
                    self.eval_stack.append(result)
                    self._emit(f"{indent}  {GREEN}handler → {result}{RESET}")
                return result
            except Exception as e:
                self._emit(f"{indent}  {RED}Handler error '{node.label}': "
                           f"{e}{RESET}")
        # ── Process builtin dispatch (31 May 2026, Adelaide) ─────────────
        if node.kind == SYMBOL_PROCESS:
            result = self._process_builtin(node, depth)
            if result is not None:
                self.eval_stack.append(result)
                self._emit(f"{indent}  {GREEN}process pushed {result!r}{RESET}")
            return None  # always continue after process

        # ── I/O subclass dispatch (31 May 2026, Adelaide) ────────────────
        if node.kind == SYMBOL_IO and getattr(self,'_io_kind_dispatch',False):
            ch, op = io_subclass(node)
            result = self._io_dispatch(node, ch, op, depth)
            if result is not None:
                self.eval_stack.append(result)
                self._emit(f"{indent}  {GREEN}I/O → pushed {result!r}{RESET}")
            return result
        return None

    # ── I/O runtime (31 May 2026, Adelaide | Stevo + Claude) ─────────────

    def _io_dispatch(self, node, ch, op, depth):
        indent = '  ' * depth
        if   ch==IO_CH_PROMPT and op==IO_OP_READ:  return self._io_prompt_read(node,indent)
        elif ch==IO_CH_PROMPT and op==IO_OP_WRITE: return self._io_prompt_write(node,indent)
        else:
            self._emit(f"{indent}  {YELLOW}[I/O] '{node.label}' "
                       f"ch={ch} op={op} — not yet implemented{RESET}")
        return None

    def _io_prompt_read(self, node, indent):
        self._emit(f"{indent}  {GREEN}[prompt-read] '{node.label}'{RESET}")
        value = None
        try:
            import tkinter as tk
            from tkinter import simpledialog
            _p = self.tk_parent
            if _p is None:
                _p = tk.Tk(); _p.withdraw()
                raw = simpledialog.askstring(node.label, f"{node.label}:", parent=_p)
                _p.destroy()
            else:
                raw = simpledialog.askstring(node.label, f"{node.label}:", parent=_p)
            if raw is not None:
                try:    value = int(raw)
                except: 
                    try: value = float(raw)
                    except: value = raw
            self._emit(f"{indent}    → received {value!r}")
        except Exception as e:
            self._emit(f"{indent}  {YELLOW}tkinter unavailable: {e}{RESET}")
            raw = input(f"  {node.label}: ")
            try:    value = int(raw)
            except: value = raw
        return value

    def _io_prompt_write(self, node, indent):
        self._emit(f"{indent}  {GREEN}[prompt-write] '{node.label}'{RESET}")
        _ = self.eval_stack.pop() if self.eval_stack else None          # discard trit
        value = self.eval_stack.pop() if self.eval_stack else '?'       # get age
        # Trit-to-message mapping preserved for future reference (e.g. a dedicated
        # trit-display output node that intentionally shows the comparison result):
        # _TRIT_MSG = {-1: 'Access denied', 0: 'Adult Supervision Required', 1: 'Access granted'}
        # if isinstance(value, int) and value in _TRIT_MSG:
        #     msg = _TRIT_MSG[value]
        msg = str(value) if value is not None else f"[{node.label}]"
        try:
            import tkinter as tk
            from tkinter import messagebox
            _p = self.tk_parent
            if _p:
                dlg = tk.Toplevel(_p)
                dlg.title(node.label)
                dlg.configure(bg='#0a0f1a')
                dlg.resizable(False, False)
                dlg.grab_set()
                tk.Label(dlg, text=msg, bg='#0a0f1a', fg='white',
                         font=('Monospace',14), padx=20, pady=16).pack()
                tk.Button(dlg, text='OK', command=dlg.destroy,
                          bg='#1a4a6b', fg='white', font=('Monospace',10),
                          relief='flat', padx=16, pady=6,
                          cursor='hand2').pack(pady=(0,12))
                dlg.bind('<Return>', lambda e: dlg.destroy())
                dlg.bind('<Escape>', lambda e: dlg.destroy())
                _p.wait_window(dlg)
            else:
                _r = tk.Tk(); _r.withdraw()
                messagebox.showinfo(node.label, msg, parent=_r)
                _r.destroy()
        except Exception:
            print(f"  [{node.label}]: {msg}")
        self._emit(f"{indent}    → displayed {msg!r}")
        return None

    # ── Process builtins (31 May 2026, Adelaide) ─────────────────────────────

    def _process_builtin(self, node, depth) -> Any:
        """
        Built-in process operations dispatched from label keywords.
        In native TernOO these are CMP/ADD/SUB instructions.
        Returns trit result or None if no builtin matched.
        """
        indent = '  ' * depth
        label = node.label.upper().replace('_',' ')
        words = label.split()

        # Extract numeric thresholds (up to two — supports range compare)
        thresholds = []
        for w in words:
            try:
                thresholds.append(int(w.strip('>=<≥≤!:')))
            except ValueError:
                pass
        threshold  = thresholds[0] if thresholds else None
        threshold2 = thresholds[1] if len(thresholds) > 1 else None

        # Comparison → push ternary trit
        # Two-threshold form (e.g. COMPARE 14 18):
        #   val <  lo  → -1
        #   lo ≤ val < hi → 0
        #   val ≥  hi  → +1
        # Single-threshold form (e.g. COMPARE 18):
        #   val < ref → -1 | val == ref → 0 | val > ref → +1
        cmp_hints = {'COMPARE','CHECK','CMP','ASSERT','VERIFY','VALIDATE','EVAL'}
        if any(w in cmp_hints for w in words):
            val = self.eval_stack[-1] if self.eval_stack else 0
            if threshold2 is not None:
                lo, hi = threshold, threshold2
                trit = -1 if val < lo else (0 if val < hi else +1)
                self._emit(f"{indent}  {GREEN}[compare] {val} in [{lo},{hi}) → trit={trit:+d}{RESET}")
            else:
                ref = threshold if threshold is not None else 0
                if any(k in words for k in ('GTE','>=','OVER','ABOVE','OLDER','ADULT')):
                    trit = +1 if val >= ref else -1
                elif any(k in words for k in ('LTE','<=','UNDER','BELOW','YOUNGER')):
                    trit = +1 if val <= ref else -1
                elif any(k in words for k in ('GT','>','GREATER')):
                    trit = +1 if val > ref else -1
                elif any(k in words for k in ('LT','<','LESS')):
                    trit = +1 if val < ref else -1
                else:
                    trit = +1 if val > ref else (0 if val == ref else -1)
                self._emit(f"{indent}  {GREEN}[compare] {val} vs {ref} → trit={trit:+d}{RESET}")
            if self.eval_stack: self.eval_stack.pop()   # pop age
            self.eval_stack.append(val)                 # push age back underneath
            return trit                                 # caller pushes trit on top

        # Arithmetic
        if 'ADD' in words or 'PLUS' in words or 'INCREMENT' in words:
            val = self.eval_stack.pop() if self.eval_stack else 0
            result = val + (threshold or 1)
            self._emit(f"{indent}  {GREEN}[add] {val}+{threshold or 1}={result}{RESET}")
            return result

        if 'SUB' in words or 'MINUS' in words or 'DECREMENT' in words:
            val = self.eval_stack.pop() if self.eval_stack else 0
            result = val - (threshold or 1)
            self._emit(f"{indent}  {GREEN}[sub] {val}-{threshold or 1}={result}{RESET}")
            return result

        if 'PUSH' in words and threshold is not None:
            self._emit(f"{indent}  {GREEN}[push] {threshold}{RESET}")
            return threshold

        # ── FILE SELECT — open file dialog, push chosen path ─────────────
        # Trigger: label contains FILE and (SELECT|CHOOSE|OPEN|PICK|LOAD|BROWSE)
        file_hints   = {'FILE','OPEN','LOAD','BROWSE'}
        select_hints = {'SELECT','CHOOSE','PICK','BROWSE','OPEN','FILE'}
        if ('FILE' in words or 'SELECT' in words or 'BROWSE' in words) and \
           (file_hints & set(words)) and (select_hints & set(words) or 'FILE' in words):
            self._emit(f"{indent}  {GREEN}[file-select] opening file dialog{RESET}")
            try:
                import tkinter as tk
                from tkinter import filedialog
                _p = self.tk_parent
                if _p is None:
                    _p = tk.Tk(); _p.withdraw()
                    path = filedialog.askopenfilename(
                        parent   = _p,
                        title    = 'Select training file for GHOST',
                        filetypes= [
                            ('TernOO GUI training', '*.tgui'),
                            ('Glade / GTK UI',      '*.ui *.glade'),
                            ('Cambalache project',  '*.cmb'),
                            ('All files',           '*.*'),
                        ]
                    )
                    _p.destroy()
                else:
                    path = filedialog.askopenfilename(
                        parent   = _p,
                        title    = 'Select training file for GHOST',
                        filetypes= [
                            ('TernOO GUI training', '*.tgui'),
                            ('Glade / GTK UI',      '*.ui *.glade'),
                            ('Cambalache project',  '*.cmb'),
                            ('All files',           '*.*'),
                        ]
                    )
                path = path or ''
                self._emit(f"{indent}    → selected {path!r}")
                return path
            except Exception as e:
                self._emit(f"{indent}  {YELLOW}file dialog unavailable: {e}{RESET}")
                return ''

        # ── TRAIN GHOST — convert + train brain on file from eval stack ───
        # Trigger: label contains TRAIN and (GHOST|BRAIN|NEURAL|AI)
        train_hints = {'TRAIN','TEACH','LEARN','FIT'}
        ghost_hints = {'GHOST','BRAIN','NEURAL','AI','MODEL'}
        if (train_hints & set(words)) and (ghost_hints & set(words)):
            path = self.eval_stack.pop() if self.eval_stack else ''
            self._emit(f"{indent}  {GREEN}[train-ghost] training on {path!r}{RESET}")
            if not path:
                self._emit(f"{indent}  {YELLOW}[train-ghost] no file path on stack — cancelled{RESET}")
                return 'No file selected'
            try:
                import importlib.util as _ilu, os as _os
                _bridge_path = _os.path.join(
                    _os.path.dirname(_os.path.abspath(__file__)),
                    'ternoo_cambalache_bridge.py')
                _spec = _ilu.spec_from_file_location('cambalache_bridge', _bridge_path)
                _bridge = _ilu.module_from_spec(_spec)
                _spec.loader.exec_module(_bridge)

                ext = _os.path.splitext(path)[1].lower()
                if ext == '.tgui':
                    tgui_path = path
                elif ext in ('.ui', '.glade', '.xml', '.cmb'):
                    tgui_path = _os.path.splitext(path)[0] + '.tgui'
                    _bridge.convert(path, tgui_path)
                    self._emit(f"{indent}    → converted to {tgui_path!r}")
                else:
                    self._emit(f"{indent}  {YELLOW}[train-ghost] unknown file type {ext!r}{RESET}")
                    return f'Unknown type: {ext}'

                _bridge.train_brain_on_tgui(tgui_path)
                fname = _os.path.basename(path)
                result = f'GHOST trained on {fname}'
                self._emit(f"{indent}    → {result}")
                return result
            except Exception as e:
                self._emit(f"{indent}  {YELLOW}[train-ghost] error: {e}{RESET}")
                return f'Training error: {e}'

        return None


    # ── Helpers ───────────────────────────────────────────────────────────────

    def _emit(self, msg: str):
        self.log.append(msg)
        if self.trace:
            print(msg)

    def set_env(self, key: str, value: Any):
        self.env[key] = value

    def push(self, value: Any):
        self.eval_stack.append(value)

    def pop(self) -> Any:
        return self.eval_stack.pop() if self.eval_stack else None


def describe_map_word(w: int) -> str:
    """Compact MAP word description for trace output."""
    try:
        d = decode_map_word(w)
        return f"{d['mode']} {d['coords']}"
    except Exception:
        return word_to_str(w)


# ── Demo programs ─────────────────────────────────────────────────────────────

def demo_linear():
    """Linear program: START → PROCESS → PROCESS → END"""
    print(f"\n{'='*56}")
    print("DEMO 1: Linear execution")
    print(f"{'='*56}")

    data = {
        'symbols': [
            {'id':1,'kind':'io',      'x':200,'y':80,  'label':'START'},
            {'id':2,'kind':'process', 'x':200,'y':200, 'label':'INIT'},
            {'id':3,'kind':'process', 'x':200,'y':320, 'label':'COMPUTE'},
            {'id':4,'kind':'io',      'x':200,'y':440, 'label':'END'},
        ],
        'edges': [
            {'src':1,'dst':2},
            {'src':2,'dst':3},
            {'src':3,'dst':4},
        ]
    }

    interp = TernOOInterpreter(trace=True)
    interp.register_handler('INIT',
        lambda n,out,stack,env: env.update({'x':42}) or print(
            f"    [INIT] env.x = 42"))
    interp.register_handler('COMPUTE',
        lambda n,out,stack,env: stack.append(env.get('x',0)*2) or print(
            f"    [COMPUTE] x*2 = {env.get('x',0)*2}"))
    interp.load_dict(data)
    result = interp.run()
    print(f"\nResult: steps={result['steps']} "
          f"stack={result['eval_stack']} env={result['env']}")


def demo_decision():
    """Decision branch: START → CHECK → (TRUE:PASS | FALSE:FAIL) → END"""
    print(f"\n{'='*56}")
    print("DEMO 2: Decision branching (ternary True/False/Maybe)")
    print(f"{'='*56}")

    data = {
        'symbols': [
            {'id':1,'kind':'io',       'x':200,'y':80,  'label':'START'},
            {'id':2,'kind':'decision', 'x':200,'y':200, 'label':'IS_POSITIVE'},
            {'id':3,'kind':'process',  'x':120,'y':320, 'label':'PASS'},
            {'id':4,'kind':'process',  'x':280,'y':320, 'label':'FAIL'},
            {'id':5,'kind':'io',       'x':200,'y':440, 'label':'END'},
        ],
        'edges': [
            {'src':1,'dst':2},
            {'src':2,'dst':3,'condition':'TRUE'},
            {'src':2,'dst':4,'condition':'FALSE'},
            {'src':3,'dst':5},
            {'src':4,'dst':5},
        ]
    }

    interp = TernOOInterpreter(trace=True)

    # Push a test value onto the stack before the decision
    interp.register_handler('START',
        lambda n,out,stack,env: stack.append(+1) or print(
            f"    [START] pushed +1 (positive/true) onto eval stack"))
    interp.register_handler('PASS',
        lambda n,out,stack,env: print(f"    [PASS] ✓ Condition was true"))
    interp.register_handler('FAIL',
        lambda n,out,stack,env: print(f"    [FAIL] ✗ Condition was false"))

    interp.load_dict(data)
    result = interp.run()
    print(f"\nResult: steps={result['steps']}")

    # Now test with negative value
    print(f"\n--- Re-run with −1 (negative/false) ---")
    interp2 = TernOOInterpreter(trace=True)
    interp2.register_handler('START',
        lambda n,out,stack,env: stack.append(-1) or print(
            f"    [START] pushed −1 (negative/false) onto eval stack"))
    interp2.register_handler('PASS',
        lambda n,out,stack,env: print(f"    [PASS] ✓ Condition was true"))
    interp2.register_handler('FAIL',
        lambda n,out,stack,env: print(f"    [FAIL] ✗ Condition was false"))
    interp2.load_dict(data)
    result2 = interp2.run()
    print(f"\nResult: steps={result2['steps']}")


def demo_loop():
    """Loop: count from 0 to 3 using a cyclic graph."""
    print(f"\n{'='*56}")
    print("DEMO 3: Loop (counter 0→3)")
    print(f"{'='*56}")

    data = {
        'symbols': [
            {'id':1,'kind':'io',       'x':200,'y':80,  'label':'START'},
            {'id':2,'kind':'process',  'x':200,'y':200, 'label':'INCREMENT'},
            {'id':3,'kind':'decision', 'x':200,'y':320, 'label':'DONE?'},
            {'id':4,'kind':'io',       'x':200,'y':440, 'label':'END'},
        ],
        'edges': [
            {'src':1,'dst':2},
            {'src':2,'dst':3},
            {'src':3,'dst':2,'condition':'FALSE'},   # loop back
            {'src':3,'dst':4,'condition':'TRUE'},    # exit
        ]
    }

    interp = TernOOInterpreter(trace=True)
    interp.set_env('counter', 0)
    interp.set_env('limit',   3)

    def increment(n, out, stack, env):
        env['counter'] += 1
        print(f"    [INCREMENT] counter = {env['counter']}")
        return env['counter']

    def done_check(n, outgoing, stack, env):
        """Decision handler signature: (node, outgoing_list, stack, env)"""
        val = env['counter'] >= env['limit']
        result = +1 if val else -1
        print(f"    [DONE?] counter={env['counter']} "
              f"limit={env['limit']} → {'DONE (+)' if val else 'CONTINUE (−)'}")
        stack.append(result)
        # Return edge index: 0=first outgoing (FALSE=loop back), 1=second (TRUE=exit)
        # edges are: [0]=FALSE(loop), [1]=TRUE(exit)
        return 1 if val else 0

    interp.register_handler('INCREMENT', increment)
    # Decision handlers take (node, outgoing_list, stack, env)
    interp.handlers['DONE?'] = done_check

    interp.load_dict(data)
    result = interp.run()
    print(f"\nResult: steps={result['steps']} "
          f"counter={result['env']['counter']}")


def demo_from_file(path: str):
    """Load and run a FlowCode JSON file."""
    print(f"\n{'='*56}")
    print(f"Running FlowCode program: {path}")
    print(f"{'='*56}")
    interp = TernOOInterpreter(trace=True)
    interp.load_flowcode(path)
    result = interp.run()
    print(f"\nSteps: {result['steps']}")
    return result


# ── Entry point ───────────────────────────────────────────────────────────────

if __name__ == '__main__':
    if '--demo' in sys.argv or len(sys.argv) == 1:
        demo_linear()
        demo_decision()
        demo_loop()
        print(f"\n{'═'*56}")
        print("All demos complete.")
        print(f"{'═'*56}")
    elif len(sys.argv) >= 2 and sys.argv[1].endswith('.json'):
        demo_from_file(sys.argv[1])
    else:
        print(__doc__)
